# set relative line mode where current line displays absolute line number
add-highlighter global/ number-lines -relative

# fzf Setup
# Load modules before setting fzf options
require-module fzf
require-module fzf-file
require-module fzf-buffer
require-module fzf-grep
# Set commands to use for fzf commands
set-option global fzf_file_command 'rg'
set-option global fzf_grep_command 'rg'
set-option global fzf_highlight_command 'bat'
# Map fzf-mode command to `<spc>f`
map -docstring 'invoke fzf-mode command' global user f ': fzf-mode<ret>'

# add keymaps for commenting out code
map -docstring 'comment-line' global normal <#> ': comment-line<ret>'
map -docstring 'comment-block' global normal <a-#> ': comment-block<ret>'

# add keymaps for working with system clipboard
map -docstring 'yank to clipboard (Wayland)' global user y '<a-|> wl-copy <ret>'
map -docstring 'paste after the end of each selection from clipboard (Wayland)' global user p '<a-!> wl-paste -n <ret>'
map -docstring 'paste before the end of each selection from clipboard (Wayland)' global user P '! wl-paste -n <ret>'
map -docstring 'replace each selection with clipboard (Wayland)' global user R '| wl-paste -n <ret>'
